name: flutter_application_1
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5 # Versi terbaru, periksa pub.dev untuk versi terbaru
  sqflite: ^2.0.0+4
  path: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_logo.png
    - assets/photobook_new.jpg
    - assets/photobook.jpg
    - assets/packaging.jpg
    - assets/STICKER-LABEL.jpg
    -  assets/tumbler.jpg
    - assets/co-card.jpg
    - assets/merchandise.jpg
        
